### ISSUE TITLE
Memory hungry bug, it seems.

### ISSUE THREAD

**Issue by ghost** [jakevdp/JSAnimation#9]
Hi Jake,

Thanks for a great plugin. It seems there is a bad memory leak somewhere. Please see here for a description: https://github.com/matplotlib/matplotlib/issues/2797. If you have time to attend to this (unfortunately, I do not at this moment), and need my code, I'll be happy to provide it.

**Comment by jakevdp** [comment]
In case someone comes across this...

Without example code it's hard to say for sure, but I suspect this is not a bug, but a side-effect of the hack upon which the package is built. The module works by creating and saving individual PNG files for each frame of your video. Depending on the size of your figure and the number of frames, you could very easily overwhelm your memory.
